### ISSUE TITLE
POM.xml missing

### ISSUE THREAD

**Issue by suraj-shingade** [RisoriTofa/A-JavaFX-Login-and-Sign-Up-Form#1]
Please upload your pom.xml or gradle file

**Comment by RisoriTofa** [comment]
Thanks for the issue, and participation @suraj-shingade 
The file has been added successfully to the project. Find it [here](https://github.com/RisoriTofa/A-JavaFX-Login-and-Sign-Up-Form/blob/main/pom.xml).
In case of any issue don't hesitate to ping me up!

**Comment by RisoriTofa** [comment]
If no other, the issue will be closed...
